apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client  # ← Was hardcoded "cloudmasa-client"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-client
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-client  # ← Must match deployment pod labels
  ports:
    - port: {{ .Values.service.client.port }}
      targetPort: {{ .Values.service.client.targetPort }}
      protocol: TCP
