apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}  # ← Add this
  labels:
    app: {{ .Release.Name }}-server
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-server
  ports:
    - port: {{ .Values.service.server.port }}
      targetPort: {{ .Values.service.server.targetPort }}
      protocol: TCP
